//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int AuthorsId { get; set; }
        public int BookId { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string Isbn { get; set; }
        public Nullable<System.DateTime> PublishingDate { get; set; }
        public string Price { get; set; }
        public string PublishHouse { get; set; }
    }
}
